---
apiVersion: v1
kind: Service
metadata:
  labels:
    layer: server
  name: vertx-http-echo-server
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    name: vertx-http-echo-server
  type: ClusterIP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vertx-http-echo-server
  labels:
    layer: server
spec:
  replicas: 3
  template:
    metadata:
      name: vertx-http-echo-server
      labels:
        name: vertx-http-echo-server
        layer: server
    spec:
      containers:
        - image: scholzj/vertx-http-echo:latest
          name: vertx-http-echo-server
          imagePullPolicy: Always
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: SERVICE_TYPE
              value: server
            - name: HTTP_HOSTNAME
              value: "0.0.0.0"
            - name: HTTP_PORT
              value: "8080"
          ports:
            - containerPort: 8080
              name: http
