---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: linkerd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: linkerd-allow-all
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: linkerd-allow-all
rules:
  - apiGroups: [""]
    resources:
      - '*'
    verbs:
      - '*'
